name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.7
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Ensure flake8 is installed and up-to-date
        run: |
          pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        uses: julianwachholz/flake8-action@v2.0.2
        with:
          checkName: 'flake8_py3' # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
